insert into sport_team (name, 'description') values ('Publix', 'Oxalis nelsonii (Small) R. Knuth');
insert into sport_team (name, 'description') values ('Venlafaxine Hydrochloride', 'Dalea emarginata (Torr. & A. Gray) Shinners');
insert into sport_team (name, 'description') values ('Hydrocortisone anti-itch plus', 'Chenopodium urbicum L.');
insert into sport_team (name, 'description') values ('Lioresal', 'Carex debilis Michx. var. strictior L.H. Bailey');
insert into sport_team (name, 'description') values ('MICONAZOLE', 'Hibiscadelphus bombycinus Forbes');
insert into sport_team (name, 'description') values ('Oxygen', 'Philadelphus oreganus Nutt. ex Torr. & A. Gray');
insert into sport_team (name, 'description') values ('Antizol', 'Orthilia secunda (L.) House');
insert into sport_team (name, 'description') values ('Escitalopram', 'Vangueria madagascariensis J.F. Gmel.');
insert into sport_team (name, 'description') values ('Monsels Solution', 'Carissa edulis (Forssk.) Vahl [excluded]');
insert into sport_team (name, 'description') values ('Desipramine Hydrochloride', 'Diplotomma ambiguum (Ach.) Flagey');
insert into sport_team (name, 'description') values ('Oxygen', 'Lupinus wyethii S. Watson ssp. wyethii');
insert into sport_team (name, 'description') values ('Atorvastatin Calcium', 'Nesaea longipes A. Gray');
insert into sport_team (name, 'description') values ('Delsym Night Time', 'Trichostomopsis brevifolia E.B. Bartram');
insert into sport_team (name, 'description') values ('Lyrica', 'Eriogonum effusum Nutt.');
insert into sport_team (name, 'description') values ('Carvedilol', 'Chionanthus domingensis Lam.');
insert into sport_team (name, 'description') values ('ecologique', 'Oncidium floridanum Ames');
insert into sport_team (name, 'description') values ('Medroxyprogesterone Acetate', 'Rubus ictus L.H. Bailey');
insert into sport_team (name, 'description') values ('Tall Ragweed', 'Pittosporum tobira (Thunb.) W.T. Aiton');
insert into sport_team (name, 'description') values ('EUPHRASIA OFFICINALIS', 'Kumlienia Greene');
insert into sport_team (name, 'description') values ('TOLNAFTATE ANTIFUNGAL', 'Coccothrinax argentata (Jacq.) L.H. Bailey');
insert into sport_team (name, 'description') values ('Carvedilol', 'Lapsana communis L.');
insert into sport_team (name, 'description') values ('Brucella Remedy', 'Poa paucispicula Scribn. & Merr.');
insert into sport_team (name, 'description') values ('THE SKIN EXTRA BB', 'Lyonia rubiginosa (Pers.) G. Don var. rubiginosa');
insert into sport_team (name, 'description') values ('ATOPALM BB LIGHT SPF 20 BROAD SPECTRUM SUNSCREEN', 'Dubautia knudsenii Hillebr. ssp. knudsenii');
insert into sport_team (name, 'description') values ('Terrasil Foot and Nail Anti-Fungal', 'Asclepias emoryi (Greene) Vail');
insert into sport_team (name, 'description') values ('fexofenadine hydrochloride', 'Paspalum millegrana Schrad.');
insert into sport_team (name, 'description') values ('EXCEL SPORT', 'Origanum maru L.');
insert into sport_team (name, 'description') values ('EXTRA STRENGTH STOOL SOFTENER LAXATIVE', 'Phlyctella andensis Nyl.');
insert into sport_team (name, 'description') values ('DOXAZOSIN', 'Triosteum aurantiacum E.P. Bicknell var. aurantiacum');
insert into sport_team (name, 'description') values ('Methylene Blue', 'Crataegus nuda Sarg.');
insert into sport_team (name, 'description') values ('MULTI PERFECTION SUPER', 'Platanthera ×channellii J.P. Folsom');
insert into sport_team (name, 'description') values ('SINGULAIR', 'Crataegus pringlei Sarg.');
insert into sport_team (name, 'description') values ('bareMinerals Prime Time BB Primer Daily Defense Broad Spectrum SPF 30', 'Stillingia sylvatica L. ssp. sylvatica');
insert into sport_team (name, 'description') values ('esika', 'Arceuthobium apachecum Hawksw. & Wiens');
insert into sport_team (name, 'description') values ('Zohydro', 'Citrullus lanatus (Thunb.) Matsum. & Nakai var. citroides (L.H. Bailey) Mansf.');
insert into sport_team (name, 'description') values ('CLE DE PEAU BEAUTE SILKY FOUNDATION I', 'Carex buxbaumii Wahlenb.');
insert into sport_team (name, 'description') values ('Multi-Active Day Early Wrinkle Correcting SPF 15', 'Austrocedrus chilensis (D. Don) Pic. Serm. & Bizzarri');
insert into sport_team (name, 'description') values ('Maxipime', 'Miconia impetiolaris (Sw.) D. Don ex DC.');
insert into sport_team (name, 'description') values ('ibuprofen', 'Cercocarpus montanus Raf.');
insert into sport_team (name, 'description') values ('flormar PERFECT COVERAGE FOUNDATION SUNSCREEN BROAD SPECTRUM SPF 15 105 Porcelain Ivory', 'Mentzelia nuda (Pursh) Torr. & A. Gray var. nuda');
insert into sport_team (name, 'description') values ('Misoprostol', 'Chenopodium humile Hook.');
insert into sport_team (name, 'description') values ('Coppertone Tanning Dry Oil', 'Justicia comata (L.) Lam.');
insert into sport_team (name, 'description') values ('Alprazolam', 'Arctostaphylos tomentosa (Pursh) Lindl. ssp. daciticola P.V. Wells');
insert into sport_team (name, 'description') values ('LOSARTAN POTASSIUM AND HYDROCHLOROTHIAZIDE', 'Cleome aculeata L.');
insert into sport_team (name, 'description') values ('Magnesium Sulfate', 'Scleria ciliata Michx.');
insert into sport_team (name, 'description') values ('desonide', 'Cotoneaster acuminatus Lindl.');
insert into sport_team (name, 'description') values ('SUPER ORIGIN CERAMIDE BB', 'Hymenoclea Torr. & A. Gray ex A. Gray');
insert into sport_team (name, 'description') values ('Furosemide', 'Pedicularis bracteosa Benth. var. flavida (Pennell) Cronquist');
insert into sport_team (name, 'description') values ('Lithium Carbonate', 'Splachnum luteum Hedw. var. luteum');
insert into sport_team (name, 'description') values ('Gericare Artificial Tears Lubricant Eye', 'Centaurium venustum (A. Gray) B.L. Rob.');
insert into sport_team (name, 'description') values ('BENZOCAINE and RESORCINOL', 'Cyanea pilosa A. Gray ssp. pilosa');
insert into sport_team (name, 'description') values ('Zaliex ALCOHOL-FREE Antiseptic Hand Sanitizer', 'Corydalis pauciflora (Stephan) Pers.');
insert into sport_team (name, 'description') values ('Levothyroxine Sodium', 'Bryum capillare Hedw. var. capillare');
insert into sport_team (name, 'description') values ('Buspirone Hydrochloride', 'Canarium schweinfurthii Engl.');
insert into sport_team (name, 'description') values ('Guaiasorb DM', 'Lecania turicensis (Hepp) Müll. Arg.');
insert into sport_team (name, 'description') values ('ZOLPIDEM TARTRATE', 'Atriplex tridentata Kuntze');
insert into sport_team (name, 'description') values ('7 Select Aspirin', 'Festuca viviparoidea Krajina ex Pavlick ssp. viviparoidea');
insert into sport_team (name, 'description') values ('Labetalol hydrochloride', 'Mimulus palmeri A. Gray');
insert into sport_team (name, 'description') values ('AVINZA', 'Cyclanthera Schrad.');
insert into sport_team (name, 'description') values ('INDIUM IN 111 CHLORIDE', 'Quercus minima (Sarg.) Small');
insert into sport_team (name, 'description') values ('Cefoxitin', 'Centrostegia thurberi A. Gray ex Benth.');
insert into sport_team (name, 'description') values ('Pediaderm AF', 'Leucothoe fontanesiana (Steud.) Sleumer');
insert into sport_team (name, 'description') values ('Berberis Vulgaris', 'Trifolium campestre Schreb.');
insert into sport_team (name, 'description') values ('propylthiouracil', 'Molendoa Lindb.');
insert into sport_team (name, 'description') values ('Blistex', 'Piper nigrum L.');
insert into sport_team (name, 'description') values ('Risperidone', 'Potamogeton ogdenii Hellquist & Hilton');
insert into sport_team (name, 'description') values ('Diphenoxylate Hydrochloride and Atropine Sulfate', 'Xanthoparmelia mougeotii (Schaerer) Hale');
insert into sport_team (name, 'description') values ('Cedar X Pet Formula', 'Kirschsteiniothelia acerina (Rossman & Wilcox) D. Hawksw.');
insert into sport_team (name, 'description') values ('LANEIGE SKIN VEIL', 'Racomitrium pacificum Irel. & Spence');
insert into sport_team (name, 'description') values ('Sunmark enema', 'Cynosurus echinatus L.');
insert into sport_team (name, 'description') values ('quetiapine fumarate', 'Agrostis clivicola Crampton var. punta-reyesensis Crampton');
insert into sport_team (name, 'description') values ('Bisacodyl', 'Lobelia niihauensis H. St. John');
insert into sport_team (name, 'description') values ('Quack Grass', 'Cheirodendron trigynum (Gaudich.) A. Heller ssp. trigynum');
insert into sport_team (name, 'description') values ('Ibuprofen', 'Allium burlewii Davidson');
insert into sport_team (name, 'description') values ('Hydromorphone Hydrochloride', 'Packera eurycephala (Torr. & A. Gray) W.A. Weber & Á. Löve var. eurycephala');
insert into sport_team (name, 'description') values ('Ondansetron', 'Packera hartiana (A. Heller) W.A. Weber & Á. Löve');
insert into sport_team (name, 'description') values ('EZ2go Zero', 'Carex louisianica L.H. Bailey');
insert into sport_team (name, 'description') values ('BACITRACIN', 'Gunnera kauaiensis Rock');
insert into sport_team (name, 'description') values ('Smelt', 'Hibiscadelphus giffardianus Rock');
insert into sport_team (name, 'description') values ('AntiBac Foam Wash/Aerogreen', 'Matthiola incana (L.) W.T. Aiton');
insert into sport_team (name, 'description') values ('Losartan Potassium', 'Berkheya Ehrh.');
insert into sport_team (name, 'description') values ('Plexion', 'Ichnanthus P. Beauv.');
insert into sport_team (name, 'description') values ('METHAZOLAMIDE', 'Cryptantha oxygona (A. Gray) Greene');
insert into sport_team (name, 'description') values ('Old Spice Fresh', 'Hymenophyllum decurrens (Jacq.) Sw.');
insert into sport_team (name, 'description') values ('Right Guard Sport', 'Zephyranthes proctorii Acev.-Rodr. & M.T. Strong');
insert into sport_team (name, 'description') values ('Acremonium strictum', 'Calochortus tolmiei Hook. & Arn.');
insert into sport_team (name, 'description') values ('Panic Ease', 'Symphyotrichum tradescantii (L.) G.L. Nesom');
insert into sport_team (name, 'description') values ('Levothyroxine Sodium', 'Dalea carthagenensis (Jacq.) J.F. Macbr. var. portoricana Barneby');
insert into sport_team (name, 'description') values ('Propranolol Hydrochloride', 'Rubus inferior L.H. Bailey');
insert into sport_team (name, 'description') values ('Leukine', 'Beta procumbens C. Sm.');
insert into sport_team (name, 'description') values ('Mustard Pollen', 'Paspalum wrightii Hitchc. & Chase');
insert into sport_team (name, 'description') values ('Oxaliplatin', 'Bouteloua uniflora Vasey');
insert into sport_team (name, 'description') values ('Diovan HCT', 'Hulsea vestita A. Gray ssp. parryi (A. Gray) Wilken');
insert into sport_team (name, 'description') values ('CAREONE', 'Symplocos Jacq.');
insert into sport_team (name, 'description') values ('Cheratussin AC', 'Calycoseris A. Gray');
insert into sport_team (name, 'description') values ('Antibacterial Foaming Hand Cleanser', 'Setariopsis auriculata (Fourn.) Scribn.');
insert into sport_team (name, 'description') values ('OXACILLIN', 'Gliricidia sepium (Jacq.) Kunth ex Walp.');
insert into sport_team (name, 'description') values ('Promethazine Hydrochloride', 'Eragrostis unioloides (Retz.) Nees ex Steud.');
insert into sport_team (name, 'description') values ('Amoxicillin', 'Astragalus diversifolius A. Gray');
insert into sport_team (name, 'description') values ('Pollens - Trees, Birch Mix', 'Lonicera sempervirens L.');
insert into sport_team (name, 'description') values ('SKIN CAVIAR CONCEALER FOUNDATION SUNSCREEN SPF 15 - Creme Blush', 'Porotrichum bigelovii (Sull.) Kindb.');
insert into sport_team (name, 'description') values ('ropinirole', 'Eriogonum microthecum Nutt.');
insert into sport_team (name, 'description') values ('Bactimicina Allergy', 'Carex krausei Boeckeler');
insert into sport_team (name, 'description') values ('Halls', 'Parmelina quercina (Willd.) Hale');
insert into sport_team (name, 'description') values ('Allergies Rocky MTNS. U.S.', 'Ceanothus fendleri A. Gray');
insert into sport_team (name, 'description') values ('Oralair', 'Scopelophila cataractae (Mitt.) Broth.');
insert into sport_team (name, 'description') values ('Fields of Flowers', 'Sabatia brachiata Elliott');
insert into sport_team (name, 'description') values ('DOXEPIN HYDROCHLORIDE', 'Eugeissona utilis Becc.');
insert into sport_team (name, 'description') values ('Omeprazole', 'Eriochrysis cayennensis P. Beauv.');
insert into sport_team (name, 'description') values ('Diltiazem Hydrochloride', 'Epiphyllum ackermanii Haw.');
insert into sport_team (name, 'description') values ('up and up pain relief', 'Tetramolopium consanguineum (A. Gray) Hillebr. ssp. leptophyllum (Sherff) Lowrey');
insert into sport_team (name, 'description') values ('Golden Pear Antibacterial Foaming Hand Wash', 'Saxifraga nelsoniana D. Don ssp. nelsoniana');
insert into sport_team (name, 'description') values ('Clarithromycin', 'Nemacladus glanduliferus Jeps.');
insert into sport_team (name, 'description') values ('04 Moisture Foundation SPF 15', 'Camissonia claviformis (Torr. & Frém.) P.H. Raven ssp. claviformis');
insert into sport_team (name, 'description') values ('RAGWITEK', 'Camissonia claviformis (Torr. & Frém.) P.H. Raven ssp. yumae (P.H. Raven) P.H. Raven');
insert into sport_team (name, 'description') values ('Tamsulosin Hydrochloride', 'Aliciella stenothyrsa (A. Gray) J.M. Porter');
insert into sport_team (name, 'description') values ('Povidone-Iodine Prep Pad', 'Vicia unijuga A. Braun');
insert into sport_team (name, 'description') values ('Baclofen', 'Mallotus Lour.');
insert into sport_team (name, 'description') values ('Hydrocortisone', 'Orthothecium diminutivum (Grout) H.A. Crum, Steere & L.E. Anderson');
insert into sport_team (name, 'description') values ('Propranolol Hydrochloride', 'Canbya Parry ex A. Gray');
insert into sport_team (name, 'description') values ('CLE DE PEAU BEAUTE SILKY FOUNDATION I', 'Croton glandulosus L. var. lindheimeri Müll. Arg.');
insert into sport_team (name, 'description') values ('CHILDRENS ALLERGY', 'Dalea scandens (Mill.) R.T. Clausen var. paucifolia (J.M. Coult.) Barneby');
insert into sport_team (name, 'description') values ('Eye Drops AC', 'Acer glabrum Torr.');
insert into sport_team (name, 'description') values ('Genuine Hand Sanitizer', 'Lupinus sericeus Pursh ssp. sericeus');
insert into sport_team (name, 'description') values ('Quetiapine fumarate', 'Desmodium canescens (L.) DC.');
insert into sport_team (name, 'description') values ('DIGOXIN', 'Vitex glabrata R. Br.');
insert into sport_team (name, 'description') values ('Aminophylline', 'Phacelia leptosepala Rydb.');
insert into sport_team (name, 'description') values ('Hot Spot', 'Carex louisianica L.H. Bailey');
insert into sport_team (name, 'description') values ('Fentanyl', 'Agalinis heterophylla (Nutt.) Small ex Britton');
insert into sport_team (name, 'description') values ('White Mulberry', 'Phleum paniculatum Huds.');
insert into sport_team (name, 'description') values ('Tegretol', 'Pisonia taina Trejo');
insert into sport_team (name, 'description') values ('ondansetron hydrochloride', 'Cenchrus palmeri Vasey');
insert into sport_team (name, 'description') values ('Gabapentin', 'Ferula gummosa Boiss.');
insert into sport_team (name, 'description') values ('Milk of Magnesia', 'Cyanea linearifolia Rock');
insert into sport_team (name, 'description') values ('Waterless Anti-Bacterial Hand Cleanser', 'Heuchera brevistaminea Wiggins');
insert into sport_team (name, 'description') values ('Peptic Relief', 'Poa sieberiana Spreng.');
insert into sport_team (name, 'description') values ('mapap', 'Physcomitrium washingtoniense H.A. Crum & L.E. Anderson');
insert into sport_team (name, 'description') values ('Oxygen', 'Epilobium canum (Greene) P.H. Raven ssp. canum');
insert into sport_team (name, 'description') values ('Anticavity Fluoride Rinse', 'Carex lacustris Willd.');
insert into sport_team (name, 'description') values ('Escitalopram Oxalate', 'Hechtia texensis S. Watson');
insert into sport_team (name, 'description') values ('Calamine Plus', 'Callitriche fassettii Schotsman');
insert into sport_team (name, 'description') values ('Green Olive', 'Lupinus sierrae-blancae Wooton & Standl.');
insert into sport_team (name, 'description') values ('CEFTRIAXONE', 'Campylopus oerstedianus (Müll. Hal.) Mitt.');
insert into sport_team (name, 'description') values ('AGARICINUM', 'Ipomoea ternifolia Cav. var. leptotoma (Torr.) J.A. McDonald');
insert into sport_team (name, 'description') values ('natural laxative', 'Piptatheropsis Romasch., P.M. Peterson & R. J. Soreng');
insert into sport_team (name, 'description') values ('Rohto', 'Phacelia linearis (Pursh) Holz.');
insert into sport_team (name, 'description') values ('Diphenhydramine Hydrochloride', 'Arctostaphylos parryana Lemmon ssp. tumescens J.E. Keeley, L. Boykin & A. Massihi');
insert into sport_team (name, 'description') values ('Hemorrhoidal Relief', 'Cuscuta cephalanthi Engelm.');
insert into sport_team (name, 'description') values ('PROBLEND Antibacterial Liquid Cleanser', 'Corema conradii (Torr.) Torr. ex Loudon');
insert into sport_team (name, 'description') values ('Cyclobenzaprine Hydrochloride', 'Nidema Britton