//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.20 at 09:42:22 PM MSK 
//


package com.example.routes.soap.soapgen.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRoutesRequest }
     * 
     */
    public GetRoutesRequest createGetRoutesRequest() {
        return new GetRoutesRequest();
    }

    /**
     * Create an instance of {@link GetRoutesResponse }
     * 
     */
    public GetRoutesResponse createGetRoutesResponse() {
        return new GetRoutesResponse();
    }

    /**
     * Create an instance of {@link RouteDTOSoap }
     * 
     */
    public RouteDTOSoap createRouteDTOSoap() {
        return new RouteDTOSoap();
    }

    /**
     * Create an instance of {@link PostRouteRequest }
     * 
     */
    public PostRouteRequest createPostRouteRequest() {
        return new PostRouteRequest();
    }

    /**
     * Create an instance of {@link RouteDTOSoapRequest }
     * 
     */
    public RouteDTOSoapRequest createRouteDTOSoapRequest() {
        return new RouteDTOSoapRequest();
    }

    /**
     * Create an instance of {@link PostRouteResponse }
     * 
     */
    public PostRouteResponse createPostRouteResponse() {
        return new PostRouteResponse();
    }

    /**
     * Create an instance of {@link GetRouteRequest }
     * 
     */
    public GetRouteRequest createGetRouteRequest() {
        return new GetRouteRequest();
    }

    /**
     * Create an instance of {@link GetRouteResponse }
     * 
     */
    public GetRouteResponse createGetRouteResponse() {
        return new GetRouteResponse();
    }

    /**
     * Create an instance of {@link PutRouteRequest }
     * 
     */
    public PutRouteRequest createPutRouteRequest() {
        return new PutRouteRequest();
    }

    /**
     * Create an instance of {@link PutRouteResponse }
     * 
     */
    public PutRouteResponse createPutRouteResponse() {
        return new PutRouteResponse();
    }

    /**
     * Create an instance of {@link DeleteRouteRequest }
     * 
     */
    public DeleteRouteRequest createDeleteRouteRequest() {
        return new DeleteRouteRequest();
    }

    /**
     * Create an instance of {@link DeleteRouteResponse }
     * 
     */
    public DeleteRouteResponse createDeleteRouteResponse() {
        return new DeleteRouteResponse();
    }

    /**
     * Create an instance of {@link DeleteDistancesRequest }
     * 
     */
    public DeleteDistancesRequest createDeleteDistancesRequest() {
        return new DeleteDistancesRequest();
    }

    /**
     * Create an instance of {@link DeleteDistancesResponse }
     * 
     */
    public DeleteDistancesResponse createDeleteDistancesResponse() {
        return new DeleteDistancesResponse();
    }

    /**
     * Create an instance of {@link GetDistancesSumRequest }
     * 
     */
    public GetDistancesSumRequest createGetDistancesSumRequest() {
        return new GetDistancesSumRequest();
    }

    /**
     * Create an instance of {@link GetDistancesSumResponse }
     * 
     */
    public GetDistancesSumResponse createGetDistancesSumResponse() {
        return new GetDistancesSumResponse();
    }

    /**
     * Create an instance of {@link GetRoutesWithGreaterDistanceRequest }
     * 
     */
    public GetRoutesWithGreaterDistanceRequest createGetRoutesWithGreaterDistanceRequest() {
        return new GetRoutesWithGreaterDistanceRequest();
    }

    /**
     * Create an instance of {@link GetRoutesWithGreaterDistanceResponse }
     * 
     */
    public GetRoutesWithGreaterDistanceResponse createGetRoutesWithGreaterDistanceResponse() {
        return new GetRoutesWithGreaterDistanceResponse();
    }

    /**
     * Create an instance of {@link CoordinateDTOSoap }
     * 
     */
    public CoordinateDTOSoap createCoordinateDTOSoap() {
        return new CoordinateDTOSoap();
    }

    /**
     * Create an instance of {@link LocationDTOSoap }
     * 
     */
    public LocationDTOSoap createLocationDTOSoap() {
        return new LocationDTOSoap();
    }

    /**
     * Create an instance of {@link LocationDTOSoapRequest }
     * 
     */
    public LocationDTOSoapRequest createLocationDTOSoapRequest() {
        return new LocationDTOSoapRequest();
    }

}
